import os
import shutil
import random
from pathlib import Path
from collections import defaultdict

# Mushroom name mapping from English to Vietnamese
# Format: "english_name": "tên_nấm_tiếng_việt"

MUSHROOM_NAMES_VI = {
    # Edible mushrooms
    "Agaricus": "nấm_mồi",
    "Agaricus_arvensis": "nấm_mồi_đồng_cỏ",
    "Agaricus_bisporus": "nấm_mồi_hai_bào_tử",
    "Agaricus_silvaticus": "nấm_mồi_rừng",
    "Aleuria_aurantia": "nấm_tai_cam",
    "almond_mushroom": "nấm_hạnh_nhân",
    "Amanita_caesarea": "nấm_vàng_hoàng_gia",
    "aniseed_funnel": "nấm_phễu_hồi_thơm",
    "Apioperdon pyriforme": "nấm_lê_hình",
    "Armillaria_mellea": "nấm_đen_sắt",
    "Auricularia_auricula-judae": "nấm_mèo_nước",
    "bay_bolete": "nấm_mũ_vịnh",
    "bearded_milkcap": "nấm_quạ_râu",
    "beechwood_sickener": "nấm_sắc_dưỡng_gỗ_sồi",
    "beefsteak_fungus": "nấm_thịt_bò",
    "birch_polypore": "nấm_lỗ_nhiều_bạch_dương",
    "birch_woodwart": "nấm_gỗ_bạch_dương",
    "black_bulgar": "nấm_đen_bungari",
    "blue_roundhead": "nấm_đầu_tròn_xanh",
    "Boletus": "nấm_ngang",
    "Boletus_badius": "nấm_ngang_nâu",
    "Boletus_edulis": "nấm_ngang_cổ_địa",
    "Boletus_reticulatus": "nấm_ngang_lưới",
    "Calbovista_subsculpta": "nấm_bóng_chùm",
    "Calocybe_gambosa": "nấm_quân_tháng_năm",
    "Calvatia_gigantea": "nấm_bóng_khổng_lồ",
    "Calvatia_utriformis": "nấm_bóng_túi",
    "Cantharellus_cibarius": "nấm_vàng_tây",
    "cauliflower_fungus": "nấm_súp_lơ",
    "cedarwood_waxcap": "nấm_mũi_gỗ_tuyết_tùng",
    "Cerioporus squamosus": "nấm_ô_rập_ốc",
    "chanterelle": "nấm_vàng",
    "chestnut_bolete": "nấm_ngang_hạt_dẻ",
    "chicken_of_the_woods": "nấm_gà_rừng",
    "Chroogomphus": "nấm_mủ_đỏ",
    "Clavariaceae": "nấm_cây_san_hô",
    "Clavulinaceae": "nấm_cây_san_hô_nhỏ",
    "Clitocybe_nuda": "nấm_cơm_tím",
    "clouded_agaric": "nấm_mây_mù",
    "clustered_domecap": "nấm_mũ_vòm_chùm",
    "Coltricia perennis": "nấm_tầng_vòng",
    "common_bonnet": "nấm_mũ_thường",
    "common_inkça": "nấm_mực_thường",
    "common_morel": "nấm_hầm_thường",
    "common_puffball": "nấm_bóng_thường",
    "common_rustgill": "nấm_mảnh_gỉ_thường",
    "Coprinellus_micaceus": "nấm_mực_lấp_lánh",
    "Coprinus comatus": "nấm_mực_xù",
    "Coprinus_comatus": "nấm_mực_xù",
    "Cortinarius_caperatus": "nấm_lưới_nước_nhiều_nếp",
    "Cortinarius_variicolor": "nấm_lưới_nhiều_màu",
    "Craterellus_cornucopioides": "nấm_vàng_sừng_phong_độc",
    "Craterellus_tubaeformis": "nấm_vàng_ống",
    "crimped_gill": "nấm_mảnh_xoắn",
    "Crucibulum laeve": "nấm_cái_trứng_lủng",
    "cucumber_cap": "nấm_mũ_dưa_chuột",
    "Cyclocybe_aegerita": "nấm_dâu_tây",
    "Cyttaria_espinosae": "nấm_gai",
    "Daedaleopsis confragosa": "nấm_bẻ_gãy",
    "Daedaleopsis tricolor": "nấm_ba_màu",
    "dryads_saddle": "nấm_yên_nữ_thần",
    "Entoloma": "nấm_mảnh_hồng",
    "fairy_ring_champignons": "nấm_vòng_tiên",
    "field_blewit": "nấm_lục_đồng",
    "field_mushroom": "nấm_chuỗi_đồng",
    "Fistulina_hepatica": "nấm_gan_thịt",
    "Flammulina velutipes": "nấm_chân_phỏng",
    "Flammulina_velutipes": "nấm_chân_phỏng",
    "fly_agaric": "nấm_ruồi_đỏ",
    "golden_bootleg": "nấm_vàng_bất_hợp_pháp",
    "golden_scalycap": "nấm_vàng_vảy",
    "golden_waxcap": "nấm_mũi_vàng",
    "Grifola_frondosa": "nấm_gà_từng_tầng",
    "heath_waxcap": "nấm_mũi_hoang_dã",
    "hen_of_the_woods": "nấm_gà_rừng_mái",
    "Hericium coralloides": "nấm_rêu_san_hô",
    "Hericium_erinaceus": "nấm_rêu_nhím",
    "honey_fungus": "nấm_mật",
    "horse_mushroom": "nấm_ngựa",
    "Hydnum_repandum": "nấm_gai_gợn",
    "Hygrocybe": "nấm_mũi",
    "Hygrophorus_chrysodon": "nấm_mũi_vàng",
    "Hypholoma fasciculare": "nấm_lửa_chùm",
    "Hypholoma lateritium": "nấm_lửa_nâu",
    "Hypsizygus_tessellatus": "nấm_tơ_tòa",
    "Kalaharituber_pfeilii": "nấm_nấm_sa_mạc",
    "Kuehneromyces mutabilis": "nấm_phổi_nâu",
    "Lactarius deliciosus": "nấm_quạ_cam",
    "Lactarius torminosus": "nấm_quạ_chứng",
    "Lactarius": "nấm_quạ",
    "Lactarius_deterrimus": "nấm_quạ_giả",
    "Lactarius_salmonicolor": "nấm_quạ_hồi",
    "Lactarius_subdulcis": "nấm_quạ_hơi_cay",
    "Lactarius_volemus": "nấm_quạ_vàng",
    "Laetiporus_sulphureus": "nấm_gà_ghi",
    "Leccinum_aurantiacum": "nấm_đầu_trắng_cam",
    "Leccinum_scabrum": "nấm_đầu_trắng_thô",
    "Leccinum_versipelle": "nấm_đầu_trắng_xoắn",
    "Lentinula_edodes": "nấm_hương",
    "lilac_bonnet": "nấm_mũ_tím",
    "lions_mane": "nấm_bầu_sư_tử",
    "Macrolepiota_procera": "nấm_dù_cao",
    "Marasmius_oreades": "nấm_vòng_tiên_산",
    "meadow_waxcap": "nấm_mũi_cỏ",
    "Merulius tremellosus": "nấm_màng_run",
    "morel": "nấm_hầm",
    "Mutinus ravenelii": "nấm_quai_quả",
    "oak_bolete": "nấm_ngang_sồi",
    "oyster_mushroom": "nấm_sò",
    "Panellus stipticus": "nấm_nhỏ_sổi_xanh",
    "parrot_waxcap": "nấm_mũi_vẹt",
    "pestle_puffball": "nấm_bóng_chày",
    "Phallus impudicus": "nấm_quai_khỏa_thân",
    "Phallus_indusiatus": "nấm_quai_nữ_thần",
    "Platismatia glauca": "nấm_mềm_xanh",
    "Pleurotus": "nấm_sò",
    "Pleurotus ostreatus": "nấm_sò_đen",
    "Pleurotus pulmonarius": "nấm_sò_trắng",
    "plums_and_custard": "nấm_mận_kem",
    "Polyporus_mylittae": "nấm_lỗ_hơi",
    "Polyporus_squamosus": "nấm_lỗ_vảy",
    "poplar_bell": "nấm_chuông_dương",
    "poplar_fieldcap": "nấm_chuông_dương_đồng",
    "porcelain_fungus": "nấm_sứ_xayda",
    "Pseudohydnum_gelatinosum": "nấm_gai_dẻo",
    "purple_brittlegill": "nấm_mảnh_tím",
    "red_cracking_bolete": "nấm_ngang_đỏ_nứt",
    "Rhizopogon_luteolus": "nấm_rễ_vàng",
    "Russula": "nấm_mảnh",
    "Schizophyllum commune": "nấm_mảnh_xẻ",
    "silky_rosegill": "nấm_hồng_lụa",
    "slippery_jack": "nấm_ngang_trơn",
    "smoky_bracket": "nấm_que_khói",
    "snowy_waxcap": "nấm_mũi_tuyết",
    "Sparassis_crispa": "nấm_súp_lơ_xây_rối",
    "spectacular_rustgill": "nấm_mảnh_gỉ_uy_nghi",
    "Stropharia aeruginosa": "nấm_xanh_bóng",
    "Stropharia_rugosoannulata": "nấm_xanh_vòng_nếp",
    "st_georges_mushroom": "nấm_tháng_ba",
    "Suillus_bovinus": "nấm_ngang_trâu",
    "Suillus_granulatus": "nấm_ngang_hạt",
    "Suillus_luteus": "nấm_ngang_vàng",
    "Suillus_tomentosus": "nấm_ngang_dãi_dạo",
    "sulphur_tuft": "nấm_lửa_vàng_chùm",
    "summer_bolete": "nấm_ngang_hè",
    "Suillus": "nấm_ngang_mịn",
    "tawny_funnel": "nấm_phễu_nâu",
    "tawny_grisette": "nấm_chúc_nâu_xám",
    "the_blusher": "nấm_đỏ_ửng",
    "the_deceiver": "nấm_người_lừa",
    "the_prince": "nấm_hoàng_tử",
    "Tremella_fuciformis": "nấm_tuyết_trắng",
    "Tricholoma_matsutake": "nấm_thông",
    "Tricholoma_terreum": "nấm_xám_đất",
    "Tuber_aestivum": "nấm_nùi_hè",
    "Tuber_borchii": "nấm_nùi_trắng",
    "Tuber_brumale": "nấm_nùi_đen",
    "Tuber_indicum": "nấm_nùi_trung_quốc",
    "Tuber_macrosporum": "nấm_nùi_hạt_lớn",
    "Tuber_mesentericum": "nấm_nùi_lưới",
    "velvet_shank": "nấm_chân_nhung",
    "Volvariella_volvacea": "nấm_nước_cơm",
    "woodland_inkcap": "nấm_mực_rừng",
    "wrinkled_peach": "nấm_đào_nhăn",

    # Poisonous mushrooms
    "Agaricus_californicus": "nấm_mồi_california",
    "Agaricus_hondensis": "nấm_mồi_hondo",
    "Agaricus_menieri": "nấm_mồi_menieri",
    "Agaricus_moelleri": "nấm_mồi_moeller",
    "Agaricus_phaeolepidotus": "nấm_mồi_vảy_nâu",
    "Agaricus_placomyces": "nấm_mồi_bẻ",
    "Agaricus_xanthodermus": "nấm_mồi_vàng_da",
    "Agrocybe_arenicola": "nấm_cát_tùng",
    "Amanita citrina": "nấm_amanita_vàng",
    "Amanita muscaria": "nấm_ruồi_đỏ",
    "Amanita pantherina": "nấm_báo",
    "Amanita rubescens": "nấm_đỏ_lẫn",
    "Amanita_abrupta": "nấm_amanita_đột_ngột",
    "Amanita_albocreata": "nấm_amanita_vòng_trắng",
    "Amanita_aprica": "nấm_amanita_nắng",
    "Amanita_boudieri": "nấm_amanita_boudier",
    "Amanita_breckonii": "nấm_amanita_breckoni",
    "Amanita_ceciliae": "nấm_amanita_cecilia",
    "Amanita_citrina": "nấm_amanita_vàng",
    "Amanita_cokeri": "nấm_amanita_cocker",
    "Amanita_cothurnata": "nấm_amanita_cơ_thúc",
    "Amanita_echinocephala": "nấm_amanita_gai_đầu",
    "Amanita_eliae": "nấm_amanita_elia",
    "Amanita_farinosa": "nấm_amanita_bột_màu",
    "Amanita_flavoconia": "nấm_amanita_màu_kem",
    "Amanita_flavorubescens": "nấm_amanita_vàng_đỏ",
    "Amanita_frostiana": "nấm_amanita_frost",
    "Amanita_gemmata": "nấm_amanita_hạt_quý",
    "Amanita_gioiosa": "nấm_amanita_gioia",
    "Amanita_gracilior": "nấm_amanita_mảnh_hơn",
    "Amanita_heterochroma": "nấm_amanita_nhiều_màu",
    "Amanita_hongoi": "nấm_amanita_hongoi",
    "Amanita_ibotengutake": "nấm_amanita_ibotengu",
    "Amanita_nehuta": "nấm_amanita_nehuta",
    "Amanita_neoovoidea": "nấm_amanita_trứng_mới",
    "Amanita_parcivolvata": "nấm_amanita_nửa_vòng",
    "Amanita_parvipantherina": "nấm_amanita_báo_nhỏ",
    "Amanita_petalinivolva": "nấm_amanita_cánh_hoa",
    "Amanita_porphyria": "nấm_amanita_tím",
    "Amanita_pseudoporphyria": "nấm_amanita_tím_giả",
    "Amanita_pseudoregalis": "nấm_amanita_vua_giả",
    "Amanita_pseudorubescens": "nấm_amanita_đỏ_giả",
    "Amanita_regalis": "nấm_amanita_vua",
    "Amanita_roseotincta": "nấm_amanita_màu_hồng",
    "Amanita_rubrovolvata": "nấm_amanita_vòng_đỏ",
    "Amanita_smithiana": "nấm_amanita_smith",
    "Amanita_subfrostiana": "nấm_amanita_frost_phụ",
    "Amanita_velatipes": "nấm_amanita_chân_màng",
    "Amanita_viscidolutea": "nấm_amanita_dính_vàng",
    "Amanita_wellsii": "nấm_amanita_wells",
    "Amanita_xanthocephala": "nấm_amanita_đầu_vàng",
    "Ampulloclitocybe_clavipes": "nấm_phễu_chân_gậy",
    "Armillaria_mellea": "nấm_đen_sắt",
    "bitter_beech_bolete": "nấm_ngang_sồi_cay",
    "Bjerkandera adusta": "nấm_khẻ_đốt",
    "blackening_brittlegill": "nấm_mảnh_đen",
    "blackening_polypore": "nấm_lỗ_đen",
    "blackening_waxcap": "nấm_mũi_đen",
    "black_morel": "nấm_hầm_đen",
    "blushing_bracket": "nấm_que_đỏ_ửng",
    "blushing_rosette": "nấm_hồng_đỏ_ửng",
    "blushing_wood_mushroom": "nấm_gỗ_đỏ_ửng",
    "bovine_bolete": "nấm_ngang_trâu",
    "bronze_bolete": "nấm_ngang_đồng",
    "brown_birch_bolete": "nấm_ngang_bạch_dương_nâu",
    "bruising_webcap": "nấm_lưới_bầm_xanh",
    "Calocera_viscosa": "nấm_sừng_dính",
    "Calycina citrina": "nấm_cốc_vàng",
    "Chlorophyllum_brunneum": "nấm_xanh_nâu",
    "Chlorophyllum_molybdites": "nấm_xanh_mol",
    "Choiromyces_venosus": "nấm_nùi_gân",
    "Clitocybe_cerussata": "nấm_bột_trắng",
    "Clitocybe_dealbata": "nấm_trắng_phấn",
    "Clitocybe_fragrans": "nấm_thơm",
    "Clitocybe_nebularis": "nấm_mây",
    "Conocybe_subovalis": "nấm_trứng_nhỏ",
    "Coprinellus_micaceus": "nấm_mực_lấp_lánh",
    "Coprinopsis atramentaria": "nấm_mực_cay",
    "Coprinopsis_alopecia": "nấm_mực_hói",
    "Coprinopsis_romagnesiana": "nấm_mực_romagna",
    "Cortinarius_bolaris": "nấm_lưới_đỏ",
    "Cortinarius_callisteus": "nấm_lưới_đẹp",
    "Cortinarius_cinnabarinus": "nấm_lưới_hồ_chi_minh",
    "Cortinarius_cinnamomeoluteus": "nấm_lưới_quế_vàng",
    "Cortinarius_cinnamomeus": "nấm_lưới_quế",
    "Cortinarius_cruentus": "nấm_lưới_máu",
    "Cortinarius_limonius": "nấm_lưới_chanh",
    "Cortinarius_malicorius": "nấm_lưới_xấu",
    "Cortinarius_mirandus": "nấm_lưới_kỳ_lạ",
    "Cortinarius_palustris": "nấm_lưới_perma",
    "Cortinarius_phoeniceus": "nấm_lưới_đỏ_phượng",
    "Cortinarius_rubicundulus": "nấm_lưới_đỏ_nhỏ",
    "Cortinarius_smithii": "nấm_lưới_smith",
    "Cudonia_circinans": "nấm_tròn_xoắn",
    "deadly_fibrecap": "nấm_xơ_chết",
    "deadly_webcap": "nấm_lưới_chết",
    "deathcap": "nấm_chết",
    "destroying_angel": "nấm_thiên_thần_hủy_diệt",
    "Echinoderma_asperum": "nấm_gai_thô",
    "Echinoderma_calcicola": "nấm_gai_xà_phòng",
    "Entoloma_albidum": "nấm_mảnh_trắng",
    "Entoloma_rhodopolium": "nấm_mảnh_hồng_cây",
    "Entoloma_sinuatum": "nấm_mảnh_xoắn",
    "false_deathcap": "nấm_chết_giả",
    "giant_puffball": "nấm_bóng_khổng_lồ",
    "greencracked_brittlegill": "nấm_mảnh_nứt_xanh",
    "grey_spotted_amanita": "nấm_amanita_chấm_xám",
    "Gyromitra esculenta": "nấm_não_giả",
    "Gyromitra gigas": "nấm_não_giả_khổng_lồ",
    "Gyromitra infula": "nấm_não_giả_mũ",
    "Gyromitra_perlata": "nấm_não_giả_hạt",
    "hairy_curtain_crust": "nấm_rèm_xù",
    "Hapalopilus_nidulans": "nấm_mềm_tổ",
    "Hebeloma_crustuliniforme": "nấm_nâu_vỏ",
    "Hebeloma_sinapizans": "nấm_nâu_moutarde",
    "hedgehog_fungus": "nấm_gai_nhím",
    "Helvella_crispa": "nấm_sốc_xoắn",
    "Helvella_dryophila": "nấm_sốc_sồi",
    "Helvella_lactea": "nấm_sốc_trắng",
    "Helvella_lacunosa": "nấm_sốc_khoét",
    "Helvella_vespertina": "nấm_sốc_tối",
    "Hypholoma_fasciculare": "nấm_lửa_chùm",
    "Hypholoma_lateritium": "nấm_lửa_nâu",
    "Hypholoma_marginatum": "nấm_lửa_viền",
    "Hypholoma_radicosum": "nấm_lửa_rễ",
    "Imperator_rhodopurpureus": "nấm_hoàng_tím",
    "Imperator_torosus": "nấm_hoàng_ngang",
    "inky_mushroom": "nấm_mực_đen",
    "Inocybe_fibrosa": "nấm_xơ_sợi",
    "Inocybe_geophylla": "nấm_xơ_đất_lá",
    "Inocybe_hystrix": "nấm_xơ_gai",
    "Inocybe_lacera": "nấm_xơ_rách",
    "Inocybe_lilacina": "nấm_xơ_tím",
    "Inocybe_rimosa": "nấm_xơ_nứt",
    "Inocybe_sambucina": "nấm_xơ_cevici",
    "Inocybe_sublilacina": "nấm_xơ_tím_phụ",
    "jelly_ears": "nấm_tai_thạch",
    "jelly_tooth": "nấm_gai_thạch",
    "king_alfreds_cakes": "nấm_vua_alfred",
    "Lactarius_chrysorrheus": "nấm_quạ_vàng_đỏ",
    "Lactarius_helvus": "nấm_quạ_sốc",
    "Lactarius_torminosus": "nấm_quạ_chứng",
    "larch_bolete": "nấm_ngang_thông_lạc_tư",
    "Lepiota_cristata": "nấm_rứa_nổi",
    "liberty_cap": "nấm_mũ_tự_do",
    "lurid_bolete": "nấm_ngang_ảm_đạm",
    "Marasmius_collinus": "nấm_khô_đồi",
    "Mycena_diosma": "nấm_mảnh_mùi",
    "Mycena_pura": "nấm_mảnh_sạch",
    "Mycena_rosea": "nấm_mảnh_hồng",
    "Neonothopanus_nambi": "nấm_sáng_nambi",
    "oak_mazegill": "nấm_sồi_mê_cung",
    "oak_polypore": "nấm_sồi_lỗ",
    "ochre_brittlegill": "nấm_mảnh_vàng",
    "old_man_of_the_woods": "nấm_ông_già_bán_rồi",
    "Omphalotus_illudens": "nấm_lừa_sáng",
    "Omphalotus_japonicus": "nấm_sáng_nhật",
    "Omphalotus_nidiformis": "nấm_sáng_tổ",
    "Omphalotus_olearius": "nấm_sáng_dầu",
    "Omphalotus_olivascens": "nấm_sáng_xanh",
    "orange_peel_fungus": "nấm_cam_vỏ",
    "Panaeolus_cinctulus": "nấm_đai_vòng",
    "panthercap": "nấm_báo_mũ",
    "Paralepistopsis_amoenolens": "nấm_thơm_đẹp_phụ",
    "parasol": "nấm_dù",
    "penny_bun": "nấm_ngang_xu",
    "peppery_bolete": "nấm_ngang_hạt_tiêu",
    "Pholiotina_rugosa": "nấm_rít_nếp",
    "Psilocybe_semilanceata": "nấm_tâm_linh_chân_không",
    "Ramaria_formosa": "nấm_nhánh_đẹp",
    "Ramaria_neoformosa": "nấm_nhánh_đẹp_mới",
    "Ramaria_pallida": "nấm_nhánh_nhạt",
    "Rubroboletus_legaliae": "nấm_ngang_đỏ_pháp",
    "Rubroboletus_lupinus": "nấm_ngang_đỏ_sói",
    "Rubroboletus_pulcherrimus": "nấm_ngang_đỏ_đẹp",
    "Rubroboletus_satanas": "nấm_ngang_đỏ_quỷ",
    "Russula_emetica": "nấm_mảnh_nôn",
    "Russula_olivacea": "nấm_mảnh_xanh",
    "Russula_subnigricans": "nấm_mảnh_đen_phụ",
    "Russula_viscida": "nấm_mảnh_dính",
    "saffron_milkcap": "nấm_quạ_nghệ_tây",
    "Sarcosphaera_coronaria": "nấm_hoàng_cốc",
    "scarletina_bolete": "nấm_ngang_đỏ_gạch",
    "scarlet_elfcup": "nấm_quỷ_đỏ",
    "scarlet_waxcap": "nấm_mũi_đỏ_rực",
    "Scleroderma_citrinum": "nấm_ngoài_vàng",
    "spotted_toughshank": "nấm_chân_cứng_chấm",
    "stinkhorn": "nấm_quai_hôi",
    "stinking_dapperling": "nấm_hạt_hôi",
    "Stropharia_aeruginosa": "nấm_xanh_bóng",
    "suede_bolete": "nấm_ngang_nhung",
    "Suillus_granulatus": "nấm_ngang_hạt",
    "the_sickener": "nấm_gây_bệnh",
    "Tricholoma_equestre": "nấm_ngựa",
    "Tricholoma_filamentosum": "nấm_sợi_chùm",
    "Tricholoma_muscarium": "nấm_ruồi_mũi",
    "Tricholoma_pardinum": "nấm_báo_mũi",
    "Tricholoma_sulphureum": "nấm_lưu_huỳnh",
    "Trogia_venenata": "nấm_độc",
    "trooping_funnel": "nấm_phễu_chùm",
    "Turbinellus_floccosus": "nấm_phễu_xù",
    "Turbinellus_kauffmanii": "nấm_phễu_kauffman",
    "turkey_tail": "nấm_gà_tây_đuôi",
    "warted_amanita": "nấm_amanita_mụn",
    "white_false_death_cap": "nấm_chết_trắng_giả",
    "white_saddle": "nấm_sốc_trắng",
    "Xanthoria parietina": "nấm_cam_tường",
    "yellow_false_truffle": "nấm_nùi_vàng_giả",
    "yellow_foot_waxcap": "nấm_mũi_chân_vàng",
    "yellow_stagshorn": "nấm_sừng_hươu_vàng",
    "yellow_stainer": "nấm_mồi_vàng_nhuộm",

    # Conditionally edible (from the earlier listing)
    "Amanita_fulva": "nấm_amanita_hung_thiêm",
    "Amanita_muscaria": "nấm_ruồi_đỏ",
    "Amanita_rubescens": "nấm_đỏ_lẫn",
    "amethyst_chanterelle": "nấm_vàng_tím",
    "amethyst_deceiver": "nấm_người_lừa_tím",
    "Armillaria borealis": "nấm_đen_sắt_bắc",
    "Artomyces pyxidatus": "nấm_cây_cốc",
    "ascot_hat": "nấm_mũ_nơ",
    "bitter_bolete": "nấm_ngang_cay",
    "brown_rollrim": "nấm_que_gốn_nâu",
    "butter_cap": "nấm_mũ_bơ",
    "Calocera viscosa": "nấm_sừng_dính",
    "Cantharellus cibarius": "nấm_vàng_tây",
    "Cetraria islandica": "nấm_du_lịch_iceland",
    "charcoal_burner": "nấm_than",
    "Chlorociboria aeruginascens": "nấm_xanh_dương",
    "Chondrostereum purpureum": "nấm_tím_rêu",
    "cinnamon_bracket": "nấm_que_quế",
    "Cladonia fimbriata": "nấm_mép_cây",
    "Cladonia rangiferina": "nấm_tuần_lộc",
    "Cladonia stellaris": "nấm_sao_cây",
    "Clitocybe nebularis": "nấm_mây",
    "common_inkcap": "nấm_mực_thường",
    "Coprinellus disseminatus": "nấm_mực_rải_rác",
    "Coprinopsis_atramentaria": "nấm_mực_cay",
    "Cortinarius": "nấm_lưới",
    "crimson_waxcap": "nấm_mũi_đỏ_thẫm",
    "curry_milkcap": "nấm_quạ_cà_ri",
    "deer_shield": "nấm_khiên_hươu",
    "devils_bolete": "nấm_ngang_quỷ",
    "dog_stinkhorn": "nấm_quai_hôi_chó",
    "dusky_puffball": "nấm_bóng_tối",
    "dyers_mazegill": "nấm_mê_cung_nhuộm",
    "earthballs": "nấm_trái_đất",
    "egghead_mottlegill": "nấm_trứng_đầu_mảnh",
    "elfin_saddle": "nấm_sốc_yêu_tinh",
    "Evernia mesomorpha": "nấm_giữa_tầng_cây",
    "Evernia prunastri": "nấm_mơ_cây",
    "false_chanterelle": "nấm_vàng_giả",
    "false_morel": "nấm_hầm_giả",
    "false_saffron_milkcap": "nấm_quạ_nghệ_tây_giả",
    "fenugreek_milkcap": "nấm_quạ_hồi_như",
    "fleecy_milkcap": "nấm_quạ_lông",
    "Fomes fomentarius": "nấm_lửa_cách_dây",
    "Fomitopsis betulina": "nấm_bạch_dương_poly",
    "Fomitopsis pinicola": "nấm_thông_poly",
    "fools_funnel": "nấm_phễu_ngốc",
    "fragrant_funnel": "nấm_phễu_thơm",
    "freckled_dapperling": "nấm_hạt_tàn_nhang",
    "frosted_chanterelle": "nấm_vàng_sương",
    "funeral_bell": "nấm_chuông_tang",
    "Ganoderma applanatum": "nấm_linh_chi_nghĩ",
    "geranium_brittlegill": "nấm_mảnh_phòng",
    "giant_funnel": "nấm_phễu_khổng_lồ",
    "glistening_inkcap": "nấm_mực_sáng",
    "Graphis scripta": "nấm_chữ_viết",
    "grey_knight": "nấm_hiệp_sĩ_xám",
    "grisettes": "nấm_chúc",
    "Gyromitra_esculenta": "nấm_não_giả",
    "hoof_fungus": "nấm_móng",
    "horn_of_plenty": "nấm_sừng_phong_độc",
    "Hygrophoropsis aurantiaca": "nấm_mũi_cam",
    "Hypogymnia physodes": "nấm_da_cây",
    "Imleria badia": "nấm_ngang_nâu",
    "Inonotus obliquus": "nấm_nám_bạch_dương",
    "jubilee_waxcap": "nấm_mũi_kỷ_niệm",
    "Lactarius_turpis": "nấm_quạ_bẩn",
    "Laetiporus sulphureus": "nấm_gà_ghi",
    "Leccinum albostipitatum": "nấm_đầu_trắng_chân",
    "Leccinum aurantiacum": "nấm_đầu_trắng_cam",
    "Leccinum scabrum": "nấm_đầu_trắng_thô",
    "Leccinum versipelle": "nấm_đầu_trắng_xoắn",
    "leccinum_albostipitatum": "nấm_đầu_trắng_chân",
    "Lepista nuda": "nấm_cơm_tím",
    "Lepista_saeva": "nấm_cơm_dã_man",
    "lilac_fibrecap": "nấm_xơ_tím",
    "Lobaria pulmonaria": "nấm_phổi_rêu",
    "Lycoperdon perlatum": "nấm_bóng_hạt",
    "Macrolepiota procera": "nấm_dù_cao",
    "macro_mushroom": "nấm_macro",
    "magpie_inkcap": "nấm_mực_họa_my",
    "medusa_mushroom": "nấm_medusa",
    "Morchella_esculenta": "nấm_hầm",
    "mosaic_puffball": "nấm_bóng_kiếng",
    "Mushrooms": "nấm",
    "Nectria cinnabarina": "nấm_đỏ_tươi",
    "orange_birch_bolete": "nấm_ngang_bạch_dương_cam",
    "orange_bolete": "nấm_ngang_cam",
    "orange_grisette": "nấm_chúc_cam",
    "pale_oyster": "nấm_sò_nhạt",
    "Parmelia sulcata": "nấm_nếp_rêu",
    "pavement_mushroom": "nấm_đá_lát",
    "Paxillus involutus": "nấm_cuộn_ngoài",
    "Peltigera aphthosa": "nấm_da_rôm",
    "Peltigera praetextata": "nấm_da_dệt",
    "Phaeophyscia orbicularis": "nấm_tròn_tối",
    "Phellinus igniarius": "nấm_lửa_mạnh",
    "Phellinus tremulae": "nấm_rung_động",
    "Phlebia radiata": "nấm_bức_xạ",
    "Pholiota aurivella": "nấm_rít_vàng",
    "Pholiota squarrosa": "nấm_rít_vảy",
    "Physcia adscendens": "nấm_leo_lên",
    "pine_bolete": "nấm_ngang_thông",
    "pink_waxcap": "nấm_mũi_hồng",
    "poison_pie": "nấm_bánh_độc",
    "powdery_brittlegill": "nấm_mảnh_bột",
    "Pseudevernia furfuracea": "nấm_vảy_rêu",
    "red_belted_bracket": "nấm_que_đai_đỏ",
    "Rhytisma acerinum": "nấm_thích_đơn",
    "rooting_bolete": "nấm_ngang_rễ",
    "rooting_shank": "nấm_chân_rễ",
    "root_rot": "nấm_thối_rễ",
    "rosy_bonnet": "nấm_mũ_hồng_tươi",
    "ruby_bolete": "nấm_ngang_hồng_ngọc",
    "Sarcomyxa serotina": "nấm_muộn_thịt",
    "Sarcoscypha austriaca": "nấm_quỷ_đỏ_áo_ích",
    "Sarcosoma globosum": "nấm_cầu_thịt",
    "scaly_wood_mushroom": "nấm_gỗ_vảy",
    "scarlet_caterpillarclub": "nấm_sâu_bột_đỏ",
    "semifree_morel": "nấm_hầm_rộng",
    "sepia_bolete": "nấm_ngang_nâu_sẫm",
    "shaggy_bracket": "nấm_que_xù",
    "shaggy_inkcap": "nấm_mực_xù",
    "shaggy_parasol": "nấm_dù_xù",
    "shaggy_scalycap": "nấm_rít_xù",
    "sheathed_woodtuft": "nấm_cây_bao",
    "silverleaf_fungus": "nấm_lá_bạc",
    "slender_parasol": "nấm_dù_mảnh",
    "slimy_waxcap": "nấm_mũi_dính",
    "snakeskin_grisette": "nấm_chúc_rắn",
    "splendid_waxcap": "nấm_mũi_lộng_lẫy",
    "splitgill": "nấm_mảnh_xẻ",
    "spring_fieldcap": "nấm_chuông_xuân",
    "Stereum hirsutum": "nấm_rêu_xù",
    "stubble_rosegill": "nấm_hồng_rơm",
    "stump_puffball": "nấm_bóng_cọc",
    "Suillus_granulatus": "nấm_ngang_hạt",
    "Suillus_grevillei": "nấm_ngang_hạt_vàng",
    "Suillus_luteus": "nấm_ngang_vàng",
    "terracotta_hedgehog": "nấm_gai_gốm",
    "the_goblet": "nấm_chén",
    "the_miller": "nấm_thợ_xay",
    "thimble_morel": "nấm_hầm_cái",
    "Trametes hirsuta": "nấm_rêu_xù_lỗ",
    "Trametes ochracea": "nấm_vàng_đất_lỗ",
    "Trametes versicolor": "nấm_đa_màu_lỗ",
    "Tremella mesenterica": "nấm_tuyết_vàng",
    "Trichaptum biforme": "nấm_hai_hình_rêu",
    "Tricholomopsis rutilans": "nấm_đỏ_rục",
    "tripe_fungus": "nấm_sách_nách",
    "truffles": "nấm_nùi",
    "tuberous_polypore": "nấm_lỗ_sần",
    "Urnula craterium": "nấm_cái_chứa",
    "vermillion_waxcap": "nấm_mũi_đỏ_tươi",
    "Verpa bohemica": "nấm_da_nước_bohemia",
    "Verpa_bohemica": "nấm_da_nước_bohemia",
    "Vulpicida pinastri": "nấm_thật_thà_thông",
    "weeping_widow": "nấm_góa_phụ_khóc",
    "white_dapperling": "nấm_hạt_trắng",
    "white_domecap": "nấm_mũ_vòm_trắng",
    "white_fibrecap": "nấm_xơ_trắng",
    "winter_chanterelle": "nấm_vàng_đông",
    "wood_blewit": "nấm_lục_gỗ",
    "wood_mushroom": "nấm_chuỗi_gỗ",
    "woolly_milkcap": "nấm_quạ_len",
    "yellow_swamp_brittlegill": "nấm_mảnh_vàng_dâm",

    # Deadly mushrooms
    "Amanita_arocheae": "nấm_amanita_arocha",
    "Amanita_bisporigera": "nấm_amanita_hai_bào_tử",
    "Amanita_exitialis": "nấm_amanita_thoát_thân",
    "Amanita_fuliginea": "nấm_amanita_khói",
    "Amanita_magnivelaris": "nấm_amanita_vòng_lớn",
    "Amanita_ocreata": "nấm_amanita_giáo",
    "Amanita_phalloides": "nấm_chết",
    "Amanita_smithiana": "nấm_amanita_smith",
    "Amanita_sphaerobulbosa": "nấm_amanita_bóng_cầu",
    "Amanita_subjunquillea": "nấm_amanita_gần_rơm",
    "Amanita_subpallidorosea": "nấm_amanita_dịu_hồng",
    "Amanita_verna": "nấm_amanita_xuân",
    "Amanita_virosa": "nấm_thiên_thần_hủy_diệt",
    "Boletus_pulcherrimus": "nấm_ngang_đỏ_đẹp",
    "Clitocybe_dealbata": "nấm_trắng_phấn",
    "Clitocybe_rivulosa": "nấm_suối",
    "Cortinarius_eartoxicus": "nấm_lưới_lỗ_tai",
    "Cortinarius_orellanus": "nấm_lưới_cao_bồi",
    "Cortinarius_rubellus": "nấm_lưới_đỏ_nhỏ",
    "Cortinarius_splendens": "nấm_lưới_sáng",
    "Entoloma_sinuatum": "nấm_mảnh_xoắn",
    "Galerina_marginata": "nấm_viền",
    "Galerina_sulciceps": "nấm_nếp_đầu",
    "Hypholoma_fasciculare": "nấm_lửa_chùm",
    "Inosperma_erubescens": "nấm_tiến_hóa_đỏ",
    "Lactarius_torminosus": "nấm_quạ_chứng",
    "Lepiota_brunneoincarnata": "nấm_rứa_nâu_hồng",
    "Lepiota_brunneolilacea": "nấm_rứa_nâu_tím",
    "Lepiota_castanea": "nấm_rứa_hạt_dẻ",
    "Lepiota_helveola": "nấm_rứa_mủ_vàng",
    "Lepiota_subincarnata": "nấm_rứa_dâu_tây",
    "Omphalotus_illudens": "nấm_sáng_lừa",
    "Omphalotus_japonicus": "nấm_sáng_nhật",
    "Paxillus_involutus": "nấm_cuộn_ngoài",
    "Pholiotina_rugosa": "nấm_rít_nếp",
    "Pleurocybella_porrigens": "nấm_sò_độc",
    "Podostroma_cornu-damae": "nấm_sừng_chết",
    "Russula_subnigricans": "nấm_mảnh_đen_phụ",
    "Tricholoma_equestre": "nấm_ngựa",
    "Trogia_venenata": "nấm_độc",
}

def organize_mushrooms():
    """Organize raw mushroom images into train/val/test folders with Vietnamese names"""
    
    raw_path = Path(r"c:\Users\loql\Desktop\train-predict\raw\Classes")
    output_path = Path(r"c:\Users\loql\Desktop\train-predict\mushroom_dataset_vi")
    
    # Create output structure
    for split in ["train", "val", "test"]:
        (output_path / split).mkdir(parents=True, exist_ok=True)
    
    # Ratios
    train_ratio = 0.70
    val_ratio = 0.15
    test_ratio = 0.15
    
    # Process each category
    categories = ["edible", "poisonous", "conditionally_edible", "deadly"]
    
    for category in categories:
        category_path = raw_path / category
        if not category_path.exists():
            continue
            
        print(f"\n{'='*60}")
        print(f"Processing {category}...")
        print(f"{'='*60}")
        
        # Get all mushroom folders in this category
        mushroom_folders = [d for d in category_path.iterdir() if d.is_dir()]
        
        for mushroom_folder in sorted(mushroom_folders):
            mushroom_name = mushroom_folder.name
            
            # Get Vietnamese name
            vi_name = MUSHROOM_NAMES_VI.get(mushroom_name, mushroom_name.lower())
            
            print(f"Processing: {mushroom_name} -> {vi_name}")
            
            # Get all image files
            image_files = list(mushroom_folder.glob("*.png")) + list(mushroom_folder.glob("*.jpg"))
            
            if not image_files:
                print(f"  Warning: No images found in {mushroom_name}")
                continue
            
            # Shuffle images
            random.shuffle(image_files)
            
            # Calculate split indices
            total = len(image_files)
            train_count = int(total * train_ratio)
            val_count = int(total * val_ratio)
            
            train_files = image_files[:train_count]
            val_files = image_files[train_count:train_count + val_count]
            test_files = image_files[train_count + val_count:]
            
            print(f"  Total images: {total} | Train: {len(train_files)} | Val: {len(val_files)} | Test: {len(test_files)}")
            
            # Create mushroom folders in each split
            for split, files in [("train", train_files), ("val", val_files), ("test", test_files)]:
                split_folder = output_path / split / vi_name
                split_folder.mkdir(parents=True, exist_ok=True)
                
                # Copy files with new names
                for idx, image_file in enumerate(files, 1):
                    extension = image_file.suffix
                    new_name = f"{vi_name}_{idx}{extension}"
                    dest_file = split_folder / new_name
                    shutil.copy2(image_file, dest_file)
    
    print(f"\n{'='*60}")
    print(f"✓ Completed! Dataset saved to: {output_path}")
    print(f"{'='*60}")

if __name__ == "__main__":
    organize_mushrooms()
